apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-binding-role
  namespace: dev
subjects:
- kind: ServiceAccount
  name: ken
  apiGroup: ""
roleRef:
  kind: Role
  name: view
  apiGroup: ""

