apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    app: web
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
  - name: web # Название контейнера
    image: gveluk55/otus-kubernetes:web # Образ из которого создается контейнер
    readinessProbe: 
      httpGet: 
        path: /index.html
        port: 80
    livenessProbe:
      tcpSocket: { port: 8000 }
      initialDelaySeconds: 15
      periodSeconds: 5
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: init-web
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
