apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prometheus
  name: prometheus-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-binding-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: prometheus
  apiGroup: ""
roleRef:
  kind: Role
  name: prometheus-pod-reader
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-binding-role
subjects:
- kind: ServiceAccount
  name: carol
  namespace: prometheus
  apiGroup: ""
roleRef:
  kind: Role
  name: prometheus-pod-reader
  apiGroup: ""