apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  #namespace: prometheus
  name: prometheus-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-binding-role
  #namespace: prometheus
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: prometheus-pod-reader
  apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
  # name: prometheus-binding-role
  # namespace: prometheus
# subjects:
# - kind: ServiceAccount
  # name: carol
  # apiGroup: ""
# roleRef:
  # kind: Role
  # name: prometheus-pod-reader
  # apiGroup: ""