apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob-binding-role
subjects:
- kind: ServiceAccount
  name: bob
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""